workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1 # Javasolt az Apple Silicon a gyorsabb buildhez

    environment:
      flutter: stable
      xcode: latest
      groups:
        - certificates # Itt kellene lenniük a Codemagic-en beállított környezeti változóknak

    scripts:
      - name: Clean project
        script: |
          flutter clean

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Precache iOS
        script: |
          flutter precache --ios

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS IPA
        script: |
          # A --no-codesign csak akkor jó, ha tényleg nem akarsz aláírást, 
          # de az IPA-hoz a Flutternek szüksége van az exportálási beállításokra.
          flutter build ipa --release --export-method ad-hoc --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app

  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable

    scripts:
      - name: Clean project
        script: |
          flutter clean
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab